# Arquivo de configuração para secrets do Streamlit
# Coloque sua API Key do Google Gemini aqui

GOOGLE_API_KEY = "AIzaSyBarB5CfRsl_M0nkQjgg-ystWV-CyzN0jU"

# Para deploy no Streamlit Cloud, você deve configurar os secrets
# através da interface web do Streamlit Cloud em:
# https://share.streamlit.io/ -> Your app -> Settings -> Secrets

